---
title: "R packages & archaeology"
---

```{r setup, include=FALSE}
metathis::meta() |>
  metathis::meta_description(
    "A collection of R packages for research and teaching in archaeology."
  ) |> 
  metathis::meta_name("github-repo" = "tesselle/packages") |> 
  metathis::meta_viewport() |> 
  metathis::meta_social(
    title = "R packages & archaeology",
    url = "https://packages.tesselle.org/",
    image = "https://www.tesselle.org/images/tesselle.png",
    image_alt = "tesselle hex sticker",
    twitter_card_type = "summary_large_image",
    twitter_creator = "@nfrerebeau"
  )

## Get packages info
repo <- utils::contrib.url("https://tesselle.r-universe.dev")
pkg <- utils::available.packages(contriburl = repo)
pkg <- as.data.frame(pkg)
url_pkg <- sprintf("https://packages.tesselle.org/%s", pkg$Package)

## Build sitemap index
loc <- paste0(url_pkg, "/sitemap.xml")
map <- sprintf("  <sitemap>\n    <loc>%s</loc>\n  </sitemap>", loc)
cat(
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  '  <sitemap>',
  '    <loc>https://packages.tesselle.org/sitemap.xml</loc>',
  '  </sitemap>',
  map,
  '</sitemapindex>',
  file = "sitemapindex.xml",
  sep = "\n",
  append = FALSE
)

## Build search index
sea <- list()
for (i in seq_along(url_pkg)) {
  path <- url_pkg[[i]]
  tmp <- try(
    expr = rjson::fromJSON(file = paste0(path, "/search.json")), 
    silent = TRUE
  )
  if (!inherits(tmp, "try-error")) {
    for (j in seq_along(tmp)) {
      tmp[[j]]$package <- pkg$Package[[i]]
    }
    sea <- c(sea, tmp)
  }
}
writeLines(rjson::toJSON(sea), "search.json")

az <- order(pkg$Package)
info <- pkg[az, c("Package", "Version", "Depends", "License")]
```

tesselle {.sidebar}
--------------------------------------------------------------------------------

[**tesselle**](https://www.tesselle.org/) is a collection of [R](https://www.r-project.org/) packages for research and teaching in archaeology. These packages focus on quantitative analysis methods developed for archaeology.

The **tesselle** packages are designed to work seamlessly together and to complement general-purpose and other specialized statistical packages.

Last update: `r Sys.Date()`.

Column {.tabset}
--------------------------------------------------------------------------------

<form role="search">
<div class="form-group">
<label for="search-input">Search in the documentation</label>
<input type="search" class="form-control" aria-label="Search" name="search-input" data-search-index="/search.json" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
</form>

### Read the documentation

```{r doc}
url_doc <- "<a href=\"%s\" title=\"Read the doc of %s (stable)\">%s</a>"
url_dev <- "<a href=\"%s/dev\" title=\"Read the doc of %s (dev)\">%s</a>"

version_stable <- sub(".9[0-9]{3}", "", info$Version)
version_stable[version_stable == "0.0.0"] <- "no stable release"
link_doc <- sprintf(url_doc, url_pkg[az], info$Package, version_stable)
link_dev <- sprintf(url_dev, url_pkg[az], info$Package, info$Version)

data <- data.frame(
  Package = info$Package,
  Stable = link_doc,
  Development = link_dev
)
knitr::kable(
  x = data, 
  row.names = FALSE,
  escape = FALSE
)
```

### CRAN check status

```{r status}
az <- order(pkg$Package)
info <- pkg[az, c("Package", "Version", "Depends", "License")]

## Get CRAN status
status <- lapply(
  X = info$Package,
  FUN = function(x) {
    api <- sprintf("https://cranchecks.info/pkgs/%s", x)
    doc <- try(rjson::fromJSON(file = api), silent = TRUE)
    if (inherits(doc, "try-error")) return(NULL)
    
    url <- doc$data$url
    chk <- doc$data$summary
    
    url_chk <- "<a href=\"%s\" title=\"CRAN check results for %s\">%s</a>"
    link_chk <- sprintf(url_chk, url, x, x)
    cbind.data.frame(link = link_chk, package = x, url = url, chk)
  }
)
status_table <- do.call(rbind, status)

knitr::kable(
  x = status_table[, -c(2, 3, 4)], 
  row.names = FALSE, 
  col.names = c("Package", "OK", "Note", "Warning", "Error", "Fail"),
  escape = FALSE
)
```

### CRAN downloads

```{r downloads-month, fig.width=7, fig.cap="CRAN downloads per month."}
source("downloads.R") # Get RStudio CRAN mirror data

downloads_month |>
  ggplot2::ggplot() +
  ggplot2::aes(x = month, y = adjusted_downloads, colour = package) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::facet_wrap(. ~ package, scales = "free_x") +
  ggplot2::scale_y_continuous(name = "Downloads per month", limits = c(0, NA)) +
  ggplot2::labs(caption = "RStudio CRAN mirror (adjusted)") +
  ggplot2::theme_bw() +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 1),
    axis.title.x = ggplot2::element_blank(),
    legend.position = "none"
  ) +
  khroma::scale_colour_bright()
```

```{r downloads-sum, eval=FALSE, fig.cap="Cumulative CRAN downloads per month."}
downloads_month |>
  ggplot2::ggplot() +
  ggplot2::aes(x = month, y = total_downloads, colour = package) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::scale_y_continuous(name = "Cumulative downloads", 
                              limits = c(0, NA)) +
  ggplot2::labs(caption = "RStudio CRAN mirror (adjusted)") +
  ggplot2::theme_bw() +
  ggplot2::theme(
    axis.text.x = ggplot2::element_text(angle = 45, hjust = 1, vjust = 1),
    axis.title.x = ggplot2::element_blank()
  ) +
  khroma::scale_colour_bright()
```

### Dependencies

```{r pkg-dep, fig.cap="Dependency graph of the tesselle packages (CRAN only)."}
tesselle <- c("arkhe", "dimensio", "folio", "kairos", "khroma", "tabula", "tesselle")
dep <- miniCRAN::makeDepGraph(tesselle, suggests = FALSE, enhances = FALSE,
                              includeBasePkgs = FALSE)

graph <- tidygraph::as_tbl_graph(dep) |>
  tidygraph::activate(nodes) |>
  dplyr::mutate(tesselle = name %in% tesselle)

set.seed(1)
ggraph::ggraph(graph, layout = 'stress') + 
  ggraph::geom_edge_link(
    mapping = ggplot2::aes(edge_colour = type),
    arrow = grid::arrow(length = grid::unit(2, "mm")),
    end_cap = ggraph::circle(3, 'mm')
  ) +
  ggraph::geom_node_point(
    mapping = ggplot2::aes(color = tesselle, size = tesselle),
    show.legend = FALSE
  ) + 
  ggraph::geom_node_text(
    mapping = ggplot2::aes(label = name),
    vjust = 0.4
  ) +
  ggplot2::theme_void() +
  ggplot2::theme(legend.position = "bottom") +
  ggraph::scale_edge_color_manual(
    name = "Dependency",
    values = c(`Depends` = "#004488", `Imports` = "#BB5566", 
               `LinkingTo` = "#DDAA33")
  ) +
  ggplot2::scale_color_manual(
    values = c(`TRUE` = "orange", `FALSE` = "lightgrey")
  ) +
  ggplot2::scale_size_manual(values = c(`TRUE` = 7, `FALSE` = 5))
```

Column {data-width=350}
--------------------------------------------------------------------------------

```{r check, include=FALSE}
cap <- c("OK", "note", "warning", "error", "fail")
col <- c("success", "info", "warning", "danger", "danger")

worst <- apply(
  X = status_table[, -c(1, 2, 3, 4)],
  MARGIN = 1,
  FUN = function(x) max(which(x > 0))
)

check <- vector(mode = "character", length = length(worst))
for (i in seq_along(worst)) {
  j <- worst[i]
  check[[i]] <- knitr::knit_expand("_boxes.Rmd")
}
```

`r paste(knitr::knit_child(text = paste(check, collapse = '\n\n')), collapse = "")`
