# https://github.com/r-hyperspec/hySpc.chondro/blob/develop/.github/workflows/drat--insert-package.yaml
on:
  workflow_call:
    inputs:
      REPO:
        required: true
        type: string
      RELEASE:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

name: drat

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: pkgbuild

      - name: Build source package
        run: |
          mkdir -p build
          Rscript -e 'pkgbuild::build(dest_path = "build", binary = FALSE, vignettes = TRUE, manual = FALSE)'

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: build

  insert:
    needs: build
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      REPO: ${{ inputs.REPO }}
      RELEASE: ${{ inputs.RELEASE }}
    steps:
      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - name: Download package
        uses: actions/download-artifact@v2
        with:
          name: package
          path: build

      - name: Configure git
        run: |
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global user.email "${REPO}@tesselle.org"
          git config --global user.name "${REPO}"

      - name: Clone tesselle/packages
        run: |
          rm -rf tmp
          git clone -b gh-pages https://github.com/tesselle/packages.git tmp

      - name: Insert package
        run: |
          install.packages("drat")
          targz <- list.files(path = "build", pattern = "\\.tar\\.gz", full.names = TRUE)
          drat::insertPackage(file = targz, repodir = "tmp", action = "archive", location = "gh-pages")
        shell: Rscript {0}

      - name: Deploy
        run: |
          cd tmp
          git add .
          # .tar.gz files are globally blocked (git ignored) by git,
          # must add manually and force it
          git add -f *.tar.gz
          git commit -m "Add ${REPO} ${RELEASE}"
          git push origin gh-pages
