# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
on:
  workflow_call:
    inputs:
      REPO:
        required: true
        type: string
      COMMIT:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

name: pkgdown

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: |
          Rscript -e 'install.packages("tekton", repos = "https://tesselle.r-universe.dev")'
          Rscript -e 'pkgdown::build_site(preview = FALSE, devel = FALSE)'

      - name: Upload site
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      REPO: ${{ inputs.REPO }}
      COMMIT: ${{ inputs.COMMIT }}
    steps:
      - name: Download site
        uses: actions/download-artifact@v2
        with:
          name: website
          path: docs

      - name: Configure git
        run: |
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git config --global user.email "${REPO}@tesselle.org"
          git config --global user.name "${REPO}"

      - name: Clone tesselle/packages
        run: |
          rm -rf tmp
          git clone -b gh-pages https://github.com/tesselle/packages.git tmp

      - name: Clean old files
        run: |
          [ -d docs/dev ] && rm -r tmp/${REPO}/dev || true
          [ ! -d docs/dev ] && rm -r tmp/${REPO}/* || true

      - name: Deploy
        run: |
          mkdir -p tmp/${REPO}
          cp -r docs/* tmp/${REPO}/
          cd tmp
          git add -A
          git commit -m "Built site for ${REPO}@$(echo ${COMMIT} | cut -c1-7)"
          git push origin gh-pages
