on:
  push:
    branches:
      - main
      - master

name: rmarkdown

jobs:
  bookdown:
    name: Render-Website

    runs-on: macOS-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "actions-user"
          git branch gh-pages 2>/dev/null
          git remote set-branches origin gh-pages
          git fetch origin gh-pages
          git worktree add --track -B gh-pages _docs origin/gh-pages

      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown", "distill"))'

      - name: Render HTML
        run: Rscript -e 'rmarkdown::render_site()'

      - name: Deploy
        if: success()
        run: |
          cp CNAME _docs/CNAME
          cp .nojekyll _docs/.nojekyll
          cp -r _site/* _docs
          cd _docs
          git add -A
          git commit -m 'Render website' || echo "nothing to commit"
          git push origin HEAD:gh-pages
